services:
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
    command: serve | ollama pull mistral

  safe-chat-api:
    build: 
      context: app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    command: 
      - fastapi
      - dev
      - app/main.py
      - --port
      - "80"
      - --host
      - "0.0.0.0"
    volumes:
      - ./app:/safe-chat/app
    env_file:
      - app/.env
    depends_on:
      - ollama

  safe-chat-bot:
    build:
      context: bot
      dockerfile: Dockerfile
    restart: always
    env_file:
      - bot/.env
    depends_on:
      - safe-chat-api

volumes:
  ollama_data: {}